### ISSUE TITLE
Errors in app.js

### ISSUE THREAD

**Issue by RXWatcher** [ricreis394/plex-library-html#4]
I have this working but it wont let you drill into the shows to get descriptions(I understand you can't drill into seasons and thats fine). I did some browser debugging and it appears to be errors on app.js. I took the app.js from your demo site and placed it into mine and it still errors so I'm not sure why it wont let me drill down on mine but works on yours.

Any ideas?

Thanks for the project!

**Comment by plckr** [comment]
What are the differences between yours and mine? You can't open the tvshow?

**Comment by RXWatcher** [comment]
1) I have a large library
2) I'm using this with this docker image: metuant/plex-library-catalog:latest which is apache
    Compose code:
```
  catalog:
    container_name: catalog
    image: metuant/plex-library-catalog:latest
    volumes:
      - ${APPDATA_ROOT}/plex-library-catalog:/var/www/html/    # your code goes into this html dir
    ports:
      - 81:80
```
3) I've added the composer+bramus/router to the vendor directory. These were the only changes.
    I have pushed to github my changes:  https://github.com/RXWatcher/plex-library-html
4) Examples. I have removed the examples but you should have them in your history otherwise if you can provide a better way of submitting them than pasting them into a github issue then I will do so.
5) The creator of the docker image is also seeing this same behavior

**Comment by plckr** [comment]
In fact it's very strange. I can see that movies load correctly, only tvshows stays loading inifnitely.
It's kinda hard to debug, but maybe could help if you check which agent you are using. Also, any way to check php logs?

**Comment by RXWatcher** [comment]
```[Tue Dec 21 14:27:30.035119 2021] [rewrite:trace1] [pid 22] mod_rewrite.c(480): [client 192.168.50.21:57276] 192.168.50.21 - - [catalog.dummy.com/sid#7f37be99ada8][rid#7f37c1ced0a0/initial] [perdir /var/www/html/] internal redirect with /api/index.php/media/1 [INTERNAL REDIRECT], referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.035199 2021] [authz_core:debug] [pid 22] mod_authz_core.c(815): [client 192.168.50.21:57276] AH01626: authorization result of Require all granted: granted, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.035206 2021] [authz_core:debug] [pid 22] mod_authz_core.c(815): [client 192.168.50.21:57276] AH01626: authorization result of <RequireAny>: granted, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.035209 2021] [core:trace3] [pid 22] request.c(360): [client 192.168.50.21:57276] request authorized without authentication by access_checker_ex hook: /api/index.php/media/1, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.035217 2021] [rewrite:trace8] [pid 22] mod_rewrite.c(480): [client 192.168.50.21:57276] 192.168.50.21 - - [catalog.dummy.com/sid#7f37be99ada8][rid#7f37c1c67bf0/initial/redir#1] [perdir /var/www/html/] Declining, no further rewriting due to END flag, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.035268 2021] [authz_core:debug] [pid 22] mod_authz_core.c(815): [client 192.168.50.21:57276] AH01626: authorization result of Require all granted: granted, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.035274 2021] [authz_core:debug] [pid 22] mod_authz_core.c(815): [client 192.168.50.21:57276] AH01626: authorization result of <RequireAny>: granted, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.035278 2021] [core:trace3] [pid 22] request.c(360): [client 192.168.50.21:57276] request authorized without authentication by access_checker_ex hook: /media/1, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.035283 2021] [rewrite:trace3] [pid 22] mod_rewrite.c(480): [client 192.168.50.21:57276] 192.168.50.21 - - [catalog.dummy.com/sid#7f37be99ada8][rid#7f37c19820a0/subreq] [perdir /var/www/html/] add path info postfix: /var/www/html/media -> /var/www/html/media/1, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.035288 2021] [rewrite:trace3] [pid 22] mod_rewrite.c(480): [client 192.168.50.21:57276] 192.168.50.21 - - [catalog.dummy.com/sid#7f37be99ada8][rid#7f37c19820a0/subreq] [perdir /var/www/html/] strip per-dir prefix: /var/www/html/media/1 -> media/1, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.035293 2021] [rewrite:trace3] [pid 22] mod_rewrite.c(480): [client 192.168.50.21:57276] 192.168.50.21 - - [catalog.dummy.com/sid#7f37be99ada8][rid#7f37c19820a0/subreq] [perdir /var/www/html/] applying pattern '^(?:api|img)/(.*)$' to uri 'media/1', referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.035297 2021] [rewrite:trace3] [pid 22] mod_rewrite.c(480): [client 192.168.50.21:57276] 192.168.50.21 - - [catalog.dummy.com/sid#7f37be99ada8][rid#7f37c19820a0/subreq] [perdir /var/www/html/] add path info postfix: /var/www/html/media -> /var/www/html/media/1, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.035308 2021] [rewrite:trace3] [pid 22] mod_rewrite.c(480): [client 192.168.50.21:57276] 192.168.50.21 - - [catalog.dummy.com/sid#7f37be99ada8][rid#7f37c19820a0/subreq] [perdir /var/www/html/] strip per-dir prefix: /var/www/html/media/1 -> media/1, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.035313 2021] [rewrite:trace3] [pid 22] mod_rewrite.c(480): [client 192.168.50.21:57276] 192.168.50.21 - - [catalog.dummy.com/sid#7f37be99ada8][rid#7f37c19820a0/subreq] [perdir /var/www/html/] applying pattern '^.*$' to uri 'media/1', referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.035322 2021] [rewrite:trace4] [pid 22] mod_rewrite.c(480): [client 192.168.50.21:57276] 192.168.50.21 - - [catalog.dummy.com/sid#7f37be99ada8][rid#7f37c19820a0/subreq] [perdir /var/www/html/] RewriteCond: input='/var/www/html/media' pattern='!-f' => matched, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.035327 2021] [rewrite:trace2] [pid 22] mod_rewrite.c(480): [client 192.168.50.21:57276] 192.168.50.21 - - [catalog.dummy.com/sid#7f37be99ada8][rid#7f37c19820a0/subreq] [perdir /var/www/html/] rewrite 'media/1' -> 'index.html', referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.035337 2021] [rewrite:trace3] [pid 22] mod_rewrite.c(480): [client 192.168.50.21:57276] 192.168.50.21 - - [catalog.dummy.com/sid#7f37be99ada8][rid#7f37c19820a0/subreq] [perdir /var/www/html/] add per-dir prefix: index.html -> /var/www/html/index.html, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.035342 2021] [rewrite:trace2] [pid 22] mod_rewrite.c(480): [client 192.168.50.21:57276] 192.168.50.21 - - [catalog.dummy.com/sid#7f37be99ada8][rid#7f37c19820a0/subreq] [perdir /var/www/html/] strip document_root prefix: /var/www/html/index.html -> /index.html, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.035346 2021] [rewrite:trace1] [pid 22] mod_rewrite.c(480): [client 192.168.50.21:57276] 192.168.50.21 - - [catalog.dummy.com/sid#7f37be99ada8][rid#7f37c19820a0/subreq] [perdir /var/www/html/] internal redirect with /index.html [INTERNAL REDIRECT], referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.053268 2021] [php:warn] [pid 22] [client 192.168.50.21:57276] PHP Warning:  Undefined array key "type" in /var/www/html/api/utils.php on line 270, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.053282 2021] [php:warn] [pid 22] [client 192.168.50.21:57276] PHP Warning:  Undefined array key "type" in /var/www/html/api/utils.php on line 270, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.053288 2021] [php:warn] [pid 22] [client 192.168.50.21:57276] PHP Warning:  Undefined array key "type" in /var/www/html/api/utils.php on line 270, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.053292 2021] [php:warn] [pid 22] [client 192.168.50.21:57276] PHP Warning:  Undefined array key "type" in /var/www/html/api/utils.php on line 270, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.053297 2021] [php:warn] [pid 22] [client 192.168.50.21:57276] PHP Warning:  Undefined array key "type" in /var/www/html/api/utils.php on line 270, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.053319 2021] [php:error] [pid 22] [client 192.168.50.21:57276] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/html/api/utils.php:97\nStack trace:\n#0 /var/www/html/api/utils.php(187): xmlArrayIfNotArray()\n#1 /var/www/html/api/utils.php(156): populateSecondaryMediaInfo()\n#2 /var/www/html/api/index.php(174): getShowData()\n#3 [internal function]: {closure}()\n#4 /var/www/html/api/vendor/bramus/router/src/Bramus/Router/Router.php(458): call_user_func_array()\n#5 /var/www/html/api/vendor/bramus/router/src/Bramus/Router/Router.php(440): Bramus\\Router\\Router->invoke()\n#6 /var/www/html/api/vendor/bramus/router/src/Bramus/Router/Router.php(287): Bramus\\Router\\Router->handle()\n#7 /var/www/html/api/index.php(250): Bramus\\Router\\Router->run()\n#8 {main}\n  thrown in /var/www/html/api/utils.php on line 97, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.053365 2021] [http:trace3] [pid 22] http_filters.c(1126): [client 192.168.50.21:57276] Response sent with status 500, headers:, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.053368 2021] [http:trace5] [pid 22] http_filters.c(1135): [client 192.168.50.21:57276]   Date: Tue, 21 Dec 2021 14:27:30 GMT, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.053370 2021] [http:trace5] [pid 22] http_filters.c(1138): [client 192.168.50.21:57276]   Server: Apache/2.4.51 (Debian), referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.053372 2021] [http:trace4] [pid 22] http_filters.c(956): [client 192.168.50.21:57276]   X-Powered-By: PHP/8.0.13, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.053373 2021] [http:trace4] [pid 22] http_filters.c(956): [client 192.168.50.21:57276]   Content-Length: 0, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.053379 2021] [http:trace4] [pid 22] http_filters.c(956): [client 192.168.50.21:57276]   Connection: close, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.053380 2021] [http:trace4] [pid 22] http_filters.c(956): [client 192.168.50.21:57276]   Content-Type: text/html; charset=UTF-8, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.053410 2021] [core:trace6] [pid 22] core_filters.c(810): [client 192.168.50.21:57276] writev_nonblocking: 211/211
[Tue Dec 21 14:28:05.721162 2021] [core:trace5] [pid 31] protocol.c(711): [client 209.141.62.11:35210] Request received from client: GET login.cgi HTTP/1.1
[Tue Dec 21 14:28:05.721196 2021] [core:debug] [pid 31] protocol.c(956): [client 209.141.62.11:35210] AH03450: HTTP Request Line; Unable to parse URI: 'login.cgi'
[Tue Dec 21 14:28:05.721218 2021] [http:trace3] [pid 31] http_filters.c(1126): [client 209.141.62.11:35210] Response sent with status 400, headers:
[Tue Dec 21 14:28:05.721221 2021] [http:trace5] [pid 31] http_filters.c(1135): [client 209.141.62.11:35210]   Date: Tue, 21 Dec 2021 14:28:05 GMT
[Tue Dec 21 14:28:05.721223 2021] [http:trace5] [pid 31] http_filters.c(1138): [client 209.141.62.11:35210]   Server: Apache/2.4.51 (Debian)
[Tue Dec 21 14:28:05.721225 2021] [http:trace4] [pid 31] http_filters.c(956): [client 209.141.62.11:35210]   Content-Length: 309
[Tue Dec 21 14:28:05.721227 2021] [http:trace4] [pid 31] http_filters.c(956): [client 209.141.62.11:35210]   Connection: close
[Tue Dec 21 14:28:05.721228 2021] [http:trace4] [pid 31] http_filters.c(956): [client 209.141.62.11:35210]   Content-Type: text/html; charset=iso-8859-1
[Tue Dec 21 14:28:05.721250 2021] [core:trace6] [pid 31] core_filters.c(810): [client 209.141.62.11:35210] writev_nonblocking: 491/491
```

**Comment by RXWatcher** [comment]
Looks like the issue is here:

```[Tue Dec 21 14:27:30.053268 2021] [php:warn] [pid 22] [client 192.168.50.21:57276] PHP Warning:  Undefined array key "type" in /var/www/html/api/utils.php on line 270, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.053282 2021] [php:warn] [pid 22] [client 192.168.50.21:57276] PHP Warning:  Undefined array key "type" in /var/www/html/api/utils.php on line 270, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.053288 2021] [php:warn] [pid 22] [client 192.168.50.21:57276] PHP Warning:  Undefined array key "type" in /var/www/html/api/utils.php on line 270, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.053292 2021] [php:warn] [pid 22] [client 192.168.50.21:57276] PHP Warning:  Undefined array key "type" in /var/www/html/api/utils.php on line 270, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.053297 2021] [php:warn] [pid 22] [client 192.168.50.21:57276] PHP Warning:  Undefined array key "type" in /var/www/html/api/utils.php on line 270, referer: https://catalog.dummy.com/1/tv-shows/1
[Tue Dec 21 14:27:30.053319 2021] [php:error] [pid 22] [client 192.168.50.21:57276] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/html/api/utils.php:97\nStack trace:\n#0 /var/www/html/api/utils.php(187): xmlArrayIfNotArray()\n#1 /var/www/html/api/utils.php(156): populateSecondaryMediaInfo()\n#2 /var/www/html/api/index.php(174): getShowData()\n#3 [internal function]: {closure}()\n#4 /var/www/html/api/vendor/bramus/router/src/Bramus/Router/Router.php(458): call_user_func_array()\n#5 /var/www/html/api/vendor/bramus/router/src/Bramus/Router/Router.php(440): Bramus\\Router\\Router->invoke()\n#6 /var/www/html/api/vendor/bramus/router/src/Bramus/Router/Router.php(287): Bramus\\Router\\Router->handle()\n#7 /var/www/html/api/index.php(250): Bramus\\Router\\Router->run()\n#8 {main}\n  thrown in /var/www/html/api/utils.php on line 97, referer: https://catalog.dummy.com/1/tv-shows/1
```

**Comment by RXWatcher** [comment]
Last comment..sorry. I'm a person who supplies too much information vs too little.

I did try various agents. I even created different libraries with different agents.it didnt seem to help.

Full traces:
Working movie trace: https://pastebin.com/VK5mL1cb
Broken tv trace: https://pastebin.com/1bWKmTh1

**Comment by RXWatcher** [comment]
Moding this in utils.php:
```
function xmlArrayIfNotArray(&$xml) {
    if (!boolval(count($xml))) return false;
    if (array_key_exists("@attributes", $xml)) return $xml = array($xml);
    return $xml;
}
```
to just

```
function xmlArrayIfNotArray(&$xml) {
    return $xml;
}
```

seems to have fixed the issue.

I dont know PHP so I'm sure its not the right way to do it...just a hack.

**Comment by deejayexe** [comment]
> 1. I have a large library
> 
>     2. I'm using this with this docker image: metuant/plex-library-catalog:latest which is apache
>        Compose code:
> 
> 
> ```
>   catalog:
>     container_name: catalog
>     image: metuant/plex-library-catalog:latest
>     volumes:
>       - ${APPDATA_ROOT}/plex-library-catalog:/var/www/html/    # your code goes into this html dir
>     ports:
>       - 81:80
> ```
> 
>     3. I've added the composer+bramus/router to the vendor directory. These were the only changes.
>        I have pushed to github my changes:  https://github.com/RXWatcher/plex-library-html
> 
>     4. Examples. I have removed the examples but you should have them in your history otherwise if you can provide a better way of submitting them than pasting them into a github issue then I will do so.
> 
>     5. The creator of the docker image is also seeing this same behavior

Can u tell me this docker image it is functional since I am trying to use it and it gives me an error **/var/www/html/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/html/' is executable**
I did a fresh install of this image and only change api settings but dont open.

@ricreis394maybe can u doing a docker image?
thanks

**Comment by RXWatcher** [comment]
my compose. I run Traefik.
```
catalog:
    container_name: catalog
    image: metuant/plex-library-catalog:latest
    volumes:
      - ${APPDATA_ROOT}/catalog:/var/www/html/
    depends_on:
      - plex1
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.catalog.rule: Host(`catalog.${TLD}`)
      traefik.http.routers.catalog.entrypoints: websecure
      traefik.http.routers.catalog.tls.options: securetls@file
      traefik.http.routers.catalog.tls: true
      traefik.http.routers.catalog.middlewares: secureHeaders@file
```
Files go here: /opt/catalog

Everything is working for me. I have my own fork with some tweaks:
https://github.com/RXWatcher/plex-library-html
